language: ruby
rbenv:
- 2.7.2
addons:
  postgresql: 9.6
before_install:
  - gem install bundler
install: gem install rails
before_script:
- cp config/database.yml.travis config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres
script:
- bundle install --jobs=3 --retry=3
- bundle exec rails db:create RAILS_ENV=test
- bundle exec rails db:migrate RAILS_ENV=test
- bundle exec rails db:seed RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
  app:
  run: rails db:migrate
