version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2
  heroku: circleci/heroku@1.2.6
jobs:
  build:
    working_directory: ~/sweater_weather
    docker:
      - image: cimg/ruby:2.7.2
        environment:
          PG_HOST: localhost
          PG_USER: circleci
      - image: circleci/postgres:13.2
        environment:
          POSTGRES_USER: sweater_weather
          POSTGRES_DB: sweater_weather_test
          POSTGRES_HOST_AUTH_METHOD: trust
    steps:
      - checkout
    
  test:
    docker:
      - image: cimg/ruby:2.7.2
        environment:
          PG_HOST: localhost
          PG_USER: circleci
      - image: circleci/postgres:13.2
        environment:
          POSTGRES_USER: sweater_weather
          POSTGRES_DB: sweater_weather_test
          POSTGRES_HOST_AUTH_METHOD: trust
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: 
            gem install bundler:2.2.19
      - run: bundle install
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Database Setup
          command: 
            bundle exec rake db:migrate RAILS_ENV=test
          environment:
            DATABASE_URL: "postgres://sweater_weather@localhost:5432/sweater_weather_test"
      - run: bundle exec rake db:schema:load --trace RAILS_ENV=test      
      - run:
          name: Test
          command:
            bundle exec rspec spec

workflows:
  heroku_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - heroku/deploy-via-git: # Use the pre-configured job, deploy-via-git
          app-name: drink-this-backend
          requires:
            - test
          filters:
            branches:
              only: main
            
            